services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: communityos-sqlserver
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourStrong!Passw0rd
    ports:
      - "1433:1433"
    volumes:
      - communityos_sqlserver_data:/var/opt/mssql

volumes:
  communityos_sqlserver_data:
